config/routes.rb
Rails.application.routes.draw do

  get 'welcome' => 'welcome#index'

  get 'documents' => 'documents#index'

  get 'players/unregistered' => 'players#unregistered'
  resources :players do
    member do
      get 'payment', action: :payment
      get 'statistic', action: :statistic
    end
  end
  resources :matches do
    collection do
      get 'payment'
    end
  end

  devise_for :users, controllers: {registrations: 'users/registrations',
                                   sessions: 'users/sessions',
                                   passwords: 'users/passwords' }, except: [:sign_up]
  resources :users, only: [:index, :update, :destroy]
  resources :results, only: [:index]
  resources :contacts, only: [:index]

  root to: "welcome#index"

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :player
  belongs_to :tournament

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  require 'will_paginate/array'
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :payment]
  before_action { @section = t('results.title') }

  # GET /players
  # GET /players.json

  def index
    @players = if params[:filter].present? && params[:filter_data].present?
      Player.where(params[:filter] => params[:filter_data])
    else
      Player.all
    end

    # handle search parameter
    if params[:search].present?
      begin
        @players = @players.search(params[:search])
        if @players.empty?
          flash.now[:alert] = t('flash.alert.search_players')
        end
      rescue ActiveRecord::StatementInvalid
        @players = Player.all.iLikeSearch(params[:search])
        if @players.empty?
          flash.now[:alert] = t('flash.alert.search_players')
        end
      end
    end
    # handle sort parameter
    sort = params[:sort]
    if sort.present?
      case sort
      when 'position'
        @players = @players.sort_by(&:position)
      else
        @players = @players.order('players.%{sort}' % { sort: sort })
      end
    else
      @players = @players.sort_by(&:position)
    end

    # handle the order parameter
    if params[:order] == "desc"
      if @players.is_a?(Array)
        @players = @players.reverse
      else
        @players = @players.reverse_order
      end
    end
    @players = @players.paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :surname, :patronymic, :comment, :best_rank, :wins,
        :losses, :created_at, :updated_at, :canton, :gender,
        :birth_year, :photo, :three_set_amount, :two_set_amount)
    end

end

app/views/results/_paginator.html.haml
- if players.any? && players.try(:total_pages).present?
  %nav
    %ul.pagination
      %li= hidden_field_tag 'total_pages', players.total_pages
      %li.left-arrow
        - if players.current_page.present? && players.current_page > 1
          = link_to results_path(filter: params[:filter], filter_data: params[:filter_data], search: params[:search], order: params[:order], sort: params[:sort], page: players.current_page-1, anchor: anchor), aria: {label: "Previous"} do
            %span{"aria-hidden"=> "true"}
              &laquo;
        - else
          %a
            %span{"aria-hidden"=> "true"}
              &laquo;

      - (1..players.total_pages).each do |page|
        %li{class: "#{"active" if page == players.current_page}"}= link_to page.to_s, results_path(filter: params[:filter], filter_data: params[:filter_data], search: params[:search], order: params[:order], sort: params[:sort], page: page), value: page
      %li.right-arrow
        - if players.try(:current_page).present? && players.current_page < players.total_pages
          = link_to results_path(filter: params[:filter], filter_data: params[:filter_data], search: params[:search], order: params[:order], sort: params[:sort], page: players.current_page+1), aria: {label: "Next"} do
            %span{"aria-hidden"=> "true"}
              &raquo;
        - else
          %a
            %span{"aria-hidden"=> "true"}
              &raquo;

app/views/results/index.html.haml
.row
  .col
    %h1.page__title= t('players.title')

-# search form
.row{style: 'margin-top: -15px;'}
  .col
    .search-form.form-group
      = form_tag results_path, method: 'get', class: 'form-inline' do
        = search_field_tag :search, params[:search], class: 'form-control', placeholder: t('players.search')
        = button_tag type: 'submit', class: 'btn btn-ghost', name: nil do
          %span.material-icons= 'search'
-if current_user.present? && current_user.super_admin?
  .row
    = link_to new_player_path, action: :create, class: 'btn btn-sstm btn-square', style: 'margin-right: auto;' do
      %span.material-icons.admin-actions__link__icon= 'add'

-# Чтобы без подзапросов
.row{style: 'margin-bottom: +15px;'}
  .col
    = link_to 'Мужской рязряд', results_path(search: params[:search], filter: 'gender', filter_data: 'male'), class: 'btn btn-ghost', style: "background: #{params[:filter_data] == 'male' ? '#E5E9EB' : 'null'}"
  .col
    = link_to 'Женский рязряд', results_path(search: params[:search], filter: 'gender', filter_data: 'female'), class: 'btn btn-ghost', style: "background: #{params[:filter_data] == 'female' ? '#E5E9EB' : 'null'}"
  .col
    = link_to 'Выстовачные матчи', results_path(search: params[:search]), class: 'btn btn-ghost', style: "background: #{params[:filter_data].nil? ? '#E5E9EB' : 'null'}"

.tab-content
  .tab-pane.fade.show.active{role: 'tabpanel', 'aria-labelledby'=>'stats-tab'}
    %table.table.table-hover.table-borderless
      %thead.table-header
        %tr
          %th.text-center= link_to t('players.position'), results_path(search: params[:search], filter: params[:filter], filter_data: params[:filter_data], sort: 'position', order: 'asc')
          %th= link_to t('players.surname'), results_path(search: params[:search], filter: params[:filter], filter_data: params[:filter_data], sort: 'surname', order: 'asc')
          %th.text-center= link_to t('players.name'), results_path(search: params[:search], filter: params[:filter], filter_data: params[:filter_data], sort: 'name', order: 'asc')
          %th.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= link_to t('players.all_games'), results_path(search: params[:search], filter: params[:filter], filter_data: params[:filter_data], sort: 'wins', order: 'asc')
          %th.text-center= link_to t('players.wins'), results_path(search: params[:search], filter: params[:filter], filter_data: params[:filter_data], sort: 'wins', order: 'asc')

      %tbody.table-content.with-show.player-list-body
        - if @players.any?
          - last_player_points = nil
          - @players.each_with_index do |player, i|
            %tr{'data-id': player.id, 'data-component'=>'player'}
              -# Сортируем по индексу всех игроков, а выводим в зависимости от выбора фильтра это gender, костыль(
              %td.text-center= player.position(params[:filter_data])
              %td
                - if player.photo.present?
                  %img{src:"data:image/png;base64,#{player.photo}",class: 'player__characters__image_micro'}
                =player.surname
              %td.text-center= player.name
              %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= player.wins.to_i + player.losses.to_i
              %td.text-center= player.wins 
              - if current_user.present? and current_user.super_admin?
                %td.admin-list-actions
                  .admin-list-actions__link
                    = link_to edit_player_path(player), class:'btn btn-ghost btn-square' do
                      %span.material-icons.admin-actions__link__icon= 'edit'
                  .admin-list-actions__link
                    = link_to player, method: :delete, data: { confirm: t('players.delete') }, class: 'btn btn-sstm btn-square' do
                      %span.material-icons.admin-actions__link__icon= 'delete'

    .player-list-footer
      = render 'paginator', players: @players, anchor: 'data'

  - if !@players.any?
    %p{style: 'text-align: center;'}
    = t('players.no_players_found')