config/routes.rb
Rails.application.routes.draw do

  get 'welcome' => 'welcome#index'

  get 'documents' => 'documents#index'

  get 'players/unregistered' => 'players#unregistered'
  resources :players do
    member do
      get 'payment', action: :payment
      get 'statistic', action: :statistic
    end
  end
  resources :matches do
    collection do
      get 'payment'
    end
  end

  devise_for :users, controllers: {registrations: 'users/registrations',
                                   sessions: 'users/sessions',
                                   passwords: 'users/passwords' }, except: [:sign_up]
  resources :users, only: [:index, :update, :destroy]
  resources :results, only: [:index]
  resources :contacts, only: [:index]

  root to: "welcome#index"

end

app/models/match.rb
class Match < ApplicationRecord
  validates :player_id_1, presence: true
  validates :player_id_2, presence: true

  validates :player1_set_1, presence: true, if: ->{ player2_set_1.present? || player2_set_2.present? || player2_set_3.present? || player1_set_2.present? || player1_set_3.present? }
  validates :player2_set_1, presence: true, if: ->{ player1_set_1.present? || player1_set_2.present? || player1_set_3.present? || player2_set_2.present? || player2_set_3.present? }
  validates :player1_set_2, presence: true, if: ->{ player2_set_2.present? || player2_set_3.present? || player1_set_3.present? }
  validates :player2_set_2, presence: true, if: ->{ player1_set_2.present? || player1_set_3.present? || player2_set_3.present? }
  validates :player1_set_3, presence: true, if: ->{ player2_set_3.present? }
  validates :player2_set_3, presence: true, if: ->{ player1_set_3.present? }

  validates :start_time, :duration, :efficiency_player_1, :efficiency_player_1, presence: true
  before_validation :default_start_time, on: [:create, :update]

  validate :check_player1, on: [:create, :update]
  validate :check_player2, on: [:create, :update]
  validate :players_eql, on: [:create, :update]
  before_update :winner_update
  before_create :winner_create
  before_destroy :destroy_players_score

  def self.search(search)
    if search
      unaccentSearch = ApplicationController.helpers.unaccent(ActiveRecord::Base.sanitize_sql_like(search))
      joins('join players on matches.player_id_1 = players.id or matches.player_id_2 = players.id')
      .where("surname ~* '.*" + unaccentSearch + ".*'" + "OR" + "name ~* '.*" + unaccentSearch + ".*'")
    else
      :all
    end
  end

  def self.iLikeSearch(search)
    if search
      sanitizedSearch = ActiveRecord::Base.sanitize_sql_like(search)
      joins('join players on matches.player_id_1 = players.id or matches.player_id_2 = players.id').
      where("name ILIKE ? or surname ILIKE ?", "%#{sanitizedSearch}%", "%#{sanitizedSearch}%")
    else
      :all
    end
  end

  def destroy_players_score
    return if winner_id.nil?

    current_loser, current_winner = player1&.id.eql?(self.winner_id) ? [player2, player1] : [player1, player2]
    current_loser&.update(losses: current_loser.losses - 1)
    current_winner&.update(wins: current_winner.wins - 1)
  end

  def winner_create
    player_winner = calc_winner
    self.winner_id = player_winner&.id
    return if player_winner.nil?

    player_winner.update(wins: player_winner.wins + 1)
    current_loser = player_winner.eql?(player1) ? player2 : player1
    current_loser.update(losses: current_loser.losses + 1)
  end

  def winner_update
    player_winner = calc_winner
    self.winner_id = player_winner&.id

    old_match = Match.find(id)
    old_winner = Player.find_by(id: old_match.winner_id)

    old_winner&.update(wins: old_winner.wins - 1)
    player_winner&.reload&.update(wins: player_winner.wins + 1)
    
    old_loser = old_match.player1.id.eql?(old_winner&.id) ? old_match.player2 : old_match.player1
    old_loser&.update(losses: old_loser.losses - 1) unless old_winner.nil?

    current_loser = player1.id.eql?(self.winner_id) ? player2 : player1
    current_loser&.reload&.update(losses: current_loser.losses + 1) unless player_winner.nil?
  end

  def calc_winner
    return nil unless player1_set_2.present? && player2_set_2.present? || player1_set_3.present? && player2_set_3.present?
    
    # TODO rafactoring
    scores = [0, 0]
    if player1_set_1 > player2_set_1
      scores[0] += 1
    elsif player1_set_1 < player2_set_1
      scores[1] += 1
    end

    if player1_set_2 > player2_set_2
      scores[0] += 1
    elsif player1_set_2 < player2_set_2
      scores[1] += 1
    end

    if player1_set_3.present? && player2_set_3.present?
      if player1_set_3 > player2_set_3
        scores[0] += 1
      elsif player1_set_3 < player2_set_3
        scores[1] += 1
      end
    end

    if scores[0] > scores[1]
      player1
    elsif scores[0] < scores[1]
      player2
    else
      nil
    end
  end

  def players_eql
    errors.add "#{player1.surname} #{player1.name}", 'не может играть сам с собой' if player_id_1.eql?(player_id_2)
  end

  def check_player1
    errors.add :player_id_1, 'Игрока1 не существует' unless Player.exists?(id: player_id_1)
  end

  def check_player2
    errors.add :player_id_2, 'Игрока2 не существует' unless Player.exists?(id: player_id_2)
  end

  def default_start_time
    self.start_time ||= Time.now
  end

  def player1
    Player.find_by(id: self.player_id_1)
  end

  def player2
    Player.find_by(id: self.player_id_2)
  end

  def player_winner
    Player.find(self.winner_id)
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  require 'will_paginate/array'
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  before_action { @section = t('matches.title') }

  # GET /matches
  # GET /matches.json
  def index
    # if params[:filter].present? && params['filter-data'].present?
    #   byebug
    #   if params[:filter] == 'canton'
    #     @matches = Player.where(canton: params['filter-data'])
    #   elsif params[:filter] == 'character'
    #     @matches = Player.where("? = ANY (main_characters)", params['filter-data'])
    #   end
    # else
      @matches = Match.all
    # end

    # handle search parameter
    if params[:search].present?
      begin
        @matches = @matches.search(params[:search])
        if @matches.empty?
          flash.now[:alert] = t('flash.alert.search_matches')
        end
      rescue ActiveRecord::StatementInvalid
        # Двойной joins не работает TODO
        @matches = Match.where(id: Match.all.iLikeSearch(params[:search]).pluck(:id))
        if @matches.empty?
          flash.now[:alert] = t('flash.alert.search_matches')
        end
      end
    end
    # handle sort parameter
    sort = params[:sort]
    if sort.present?
      case sort
      when 'player1'
        @matches = @matches.joins('join players on matches.player_id_1 = players.id').order("players.surname")
      when 'player2'
        @matches = @matches.joins('join players on matches.player_id_2 = players.id').order("players.surname")
      when 'winner'
        @matches = @matches.joins('join players on matches.winner_id=players.id').order("players.surname").order("players.surname")
      else
        @matches = @matches.order("matches.?".gsub('?', params[:sort]))
      end
    else
      @matches = @matches.order(created_at: :desc)
    end
    @matches = @matches.paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
    # handle the order parameter
    if params[:order] == "desc" and !@matches.is_a?(Array)
      @matches = @matches.reverse_order
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    set_match
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # # POST /matches
  # # POST /matches.json
  def create
    @match = Match.new(match_params)
  
    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: t('flash.notice.match_created') }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        # render
        format.html { redirect_to @match, notice: t('flash.notice.match_updated') }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user.super_admin? or current_user.is_admin?
      if @match.destroy
        # render
        redirect_to matches_path, notice: t('flash.notice.match_destroyed')
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def payment
    return if params.dig(:date, :month).blank?

    @payment = true
    players = Player.all.map do |player|
      PlayerPayment.new(player, params['date']['month'].to_i, params['date']['year'].to_i).call.merge(full_name: player.full_name)
    end
    @month_payment = {
      all_amount: players.sum{ |player| player[:all_amount] },
      players: players
    }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:player_id_1, :player_id_2, :player1_set_1, :player1_set_2, :player1_set_3, :player2_set_1, 
        :player2_set_2, :player2_set_3, :start_time, :winner, :created_at, :updated_at, :efficiency_player_2, :efficiency_player_1, :duration)
    end

end

app/helpers/match_helper.rb
module MatchHelper
  def players_for_select
    Player.order(:surname).pluck(:id, :name, :surname).each_with_object({}) do |arr, hash|
      hash[[arr[2], arr[1]].join(' ')] = arr.first.to_i
    end
  end
end

app/views/matches/_form.html.haml
= form_for @match, role: 'form', class:'form' do |f|

  - if @match.errors.any?
    #error_explanation
      %h2= t('matches.prohibited')
      %ul
        - @match.errors.full_messages.each do |message|
          %li= message
  - if current_user.super_admin? || current_user.is_admin?
    .row
      .col
        .field.form-group
          = f.label :name, t('matches.start_time')
          = f.datetime_select :start_time, :start_year => Date.current.year, include_blank: false, default: {"start_time(3i)"=>Time.current.day.to_s, "start_time(2i)"=>Time.current.month.to_s, "start_time(1i)"=>Time.current.year.to_s, "start_time(4i)"=>"12", "start_time(5i)"=>"00"}
      .col
        .field.form-group
          = f.label :name, t('matches.duration')
          = f.number_field :duration, min:0, include_blank: false, class: 'form-control'
    .row
      .col
        .field.form-group
          = f.label :name, t('matches.player1')
          = f.select :player_id_1, options_for_select(players_for_select, @match.player_id_1), {include_blank: false}, class: 'form-control'
      .col  
        .field.form-group
          = f.label :name, t('matches.set_1')
          = f.number_field :player1_set_1, min:0, max:7, include_blank: true, class: 'form-control'
      .col
        .field.form-group
          = f.label :name, t('matches.set_2')
          = f.number_field :player1_set_2, min:0, max:7, include_blank: true, class: 'form-control'
      .col
        .field.form-group
          = f.label :name, t('matches.set_3')
          = f.number_field :player1_set_3, min:0, max:7, include_blank: true, class: 'form-control'
      .col
        .field.form-group
          = f.label :name, t('matches.efficiency')
          = f.number_field :efficiency_player_1, include_blank: false, class: 'form-control'
    .row
      .col
        .field.form-group
          = f.label :name, t('matches.player2')
          = f.select :player_id_2, options_for_select(players_for_select, @match.player_id_2), {include_blank: false}, class: 'form-control'
      .col
        .field.form-group
          = f.label :name, t('matches.set_1')
          = f.number_field :player2_set_1, min:0, max:7, include_blank: true, class: 'form-control'
      .col
        .field.form-group
          = f.label :name, t('matches.set_2')
          = f.number_field :player2_set_2, min:0, max:7, include_blank: true, class: 'form-control'
      .col
        .field.form-group
          = f.label :name, t('matches.set_3')
          = f.number_field :player2_set_3, min:0, max:7, include_blank: true, class: 'form-control'
      .col
        .field.form-group
          = f.label :name, t('matches.efficiency')
          = f.number_field :efficiency_player_2, include_blank: false, class: 'form-control'

  .actions.form-group
    = f.submit class:'btn btn-ghost', value: t('matches.save')

app/views/matches/_paginator.html.haml
- if matches.any? && matches.try(:total_pages).present?
  %nav
    %ul.pagination
      %li= hidden_field_tag 'total_pages', matches.total_pages
      %li.left-arrow
        - if matches.current_page.present? && matches.current_page > 1
          = link_to matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: matches.current_page-1), aria: {label: "Previous"} do
            %span{"aria-hidden"=> "true"}
              &laquo;
        - else
          %a
            %span{"aria-hidden"=> "true"}
              &laquo;

      - truncate_count = 4
      - if matches.total_pages > truncate_count * 2
        -# truncate
        - if matches.current_page < truncate_count
          - (1..truncate_count + 1).each do |page|
            %li{class: "#{"active" if page == matches.current_page}"}= link_to page.to_s, matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: page), value: page
          %li= link_to '...', matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: matches.current_page), value: matches.current_page
          %li{class: "#{"active" if matches.total_pages == matches.current_page}"}= link_to matches.total_pages.to_s, matches_path(search: params[:search], order: params[:order], sort: params[:sort], page:  matches.total_pages), value:  matches.total_pages
        - elsif matches.current_page >  matches.total_pages - truncate_count
          %li{class: "#{"active" if 1 == matches.current_page}"}= link_to 1.to_s, matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: 1), value: 1
          %li= link_to '...', matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: matches.current_page), value: matches.current_page
          - (matches.total_pages-truncate_count..matches.total_pages).each do |page|
            %li{class: "#{"active" if page == matches.current_page}"}= link_to page.to_s, matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: page), value: page
        - else
          %li{class: "#{"active" if 1 == matches.current_page}"}= link_to 1.to_s, matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: 1), value: 1
          %li= link_to '...', matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: matches.current_page), value: matches.current_page
          - pol_truncate_count = 1
          - (matches.current_page-pol_truncate_count..matches.current_page+pol_truncate_count).each do |page|
            %li{class: "#{"active" if page == matches.current_page}"}= link_to page.to_s, matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: page), value: page
          %li= link_to '...', matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: matches.current_page), value: matches.current_page
          %li{class: "#{"active" if matches.total_pages == matches.current_page}"}= link_to matches.total_pages.to_s, matches_path(search: params[:search], order: params[:order], sort: params[:sort], page:  matches.total_pages), value:  matches.total_pages
      - else
        - (1..matches.total_pages).each do |page|
          %li{class: "#{"active" if page == matches.current_page}"}= link_to page.to_s, matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: page), value: page
      %li.right-arrow
        - if matches.try(:current_page).present? && matches.current_page < matches.total_pages
          = link_to matches_path(search: params[:search], order: params[:order], sort: params[:sort], page: matches.current_page+1), aria: {label: "Next"} do
            %span{"aria-hidden"=> "true"}
              &raquo;
        - else
          %a
            %span{"aria-hidden"=> "true"}
              &raquo;

app/views/matches/_past_tournaments.html.haml
- if past_tournaments.any?
  .player__tournaments
    %table.table.table-hover.table-borderless
      %thead.table-header
        %tr
          %th{colspan: '2'}
            %h3= t('players.past_tournaments') + ' ' + year
          %th.text-center #
      %tbody.table-content.with-show
        - past_tournaments.order(date: :desc).each do |tournament|
          %tr{'data-id': tournament.id, 'data-component'=>'tournament'}
            %td= tournament.name
            %td
              - if tournament.location.present?
                = tournament.location.split(',')[0]
              - else
                = tournament.city || '-'
            %td.text-center
              - player_rank = '-'
              - if tournament.ranking_string.to_s.include?(player.gamer_tag)
                - tournament.ranking_string.split(';').sort.each do |r|
                  - if r.split(',')[1] == player.gamer_tag
                    - player_rank = r.split(',')[0]
              - if player_rank == '-' or player_rank.nil? or player_rank.empty?
                - player_rank = '-'
              - else
                - player_rank = player_rank.to_i.ordinalize
              %strong= "#{player_rank}"

app/views/matches/_show_payment.html.haml
.tab-content
  .tab-pane.fade.show.active{role: 'tabpanel', 'aria-labelledby'=>'stats-tab'}
    %table.table.table-hover.table-borderless
      %thead.table-header
        %tr
          %th.text-center= t("players.fio")
          %th.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= t("players.count_set_2")
          %th.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= t("players.count_set_3")
          %th.text-center= t("players.price_set_2")
          %th.text-center= t("players.price_set_3")
          %th.text-center= t("players.price_sets")
          %th.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= t("players.average_time")
          %th.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= t("players.efficiency")
      %tbody.table-content.with-show.player-list-body
        %td.text-center
          - @month_payment[:players].each do |player| 
            %tr{'data-id': player[:id], 'data-component'=>'player'}
              %td.text-center= player[:full_name]
              %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= player[:all_count_set_2]
              %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= player[:all_count_set_3]
              %td.text-center= player[:all_price_set_2]
              %td.text-center= player[:all_price_set_3]
              %td.text-center= player[:all_amount]
              %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= player[:all_average_time]
              %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= player[:all_efficiency]
.player__stats 
  .row
    .col
      %strong
        = t('players.price')
      %span
        = @month_payment[:all_amount]
          

app/views/matches/edit.html.haml
.row
  .col
    %h1.page__title= t('matches.edit')

.row
  .col
    = render 'form', match: @match

app/views/matches/index.html.haml
.row
  .col
    %h1.page__title= t('matches.title')

-# search form
.row{style: 'margin-top: -15px;'}
  .col
    .search-form.form-group
      = form_tag matches_path, method: 'get', class: 'form-inline' do
        = search_field_tag :search, params[:search], class: 'form-control', placeholder: t('players.search')
        = button_tag type: 'submit', class: 'btn btn-ghost', name: nil do
          %span.material-icons= 'search'
- if current_user.present?
  .admin-actions
    -if current_user.super_admin? || current_user.is_admin?
      .admin-actions__link
        = link_to new_match_path, action: :create, class: 'btn btn-sstm btn-square', style: 'margin-right: auto;' do
          %span.material-icons.admin-actions__link__icon= 'add'
    - if current_user.is_accountant
      .admin-actions__link
        = link_to payment_matches_path, method: :get, class: 'btn btn-sstm btn-square' do
          %span.material-icons.admin-actions__link__icon= 'payment'
-# связать таблицы бд, чтобы не было n + 1
- players = Player.where(id: @matches.flat_map {|match| [match.player_id_1, match.player_id_2]}.uniq).pluck(:id, :surname, :name, :photo).each_with_object({}) {|player, hash| hash[player[0]] = {surname: player[1], name: player[2], photo: player[3]}}
.tab-content#matches-tabs-content
  .tab-pane.fade.show.active{role: 'tabpanel', 'aria-labelledby'=>'stats-tab'}
    %table.table.table-hover.table-borderless
      %thead.table-header
        %tr
          %th= link_to t('matches.player1'), matches_path(search: params[:search], filter: params[:filter], 'filter-data': params['filter-data'], sort: 'player1', order: 'asc')
          %th.text-center= link_to t('matches.player2'), matches_path(search: params[:search], filter: params[:filter], 'filter-data': params['filter-data'], sort: 'player2', order: 'asc')
          %th.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= link_to t('matches.start_time'), matches_path(search: params[:search], filter: params[:filter], 'filter-data': params['filter-data'], sort: 'start_time', order: 'asc')
          %th.text-center= link_to t('matches.winner'), matches_path(search: params[:search], filter: params[:filter], 'filter-data': params['filter-data'], sort: 'winner', order: 'asc')
      %tbody.table-content.with-show.player-list-body
        - if @matches.any?
          - @matches.each_with_index do |match, i|
            %tr{'data-id': match.id, 'data-component'=>'matche'}
              %td
                - if players[match.player_id_1][:photo].present?
                  %img{src:"data:image/png;base64,#{players[match.player_id_1][:photo]}",class: 'player__characters__image_micro'}
                = [players[match.player_id_1][:surname], players[match.player_id_1][:name]].join(' ')
              %td.text-center
                - if players[match.player_id_2][:photo].present?
                  %img{src:"data:image/png;base64,#{players[match.player_id_2][:photo]}",class: 'player__characters__image_micro'}
                = [players[match.player_id_2][:surname], players[match.player_id_2][:name]].join(' ')
              %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= match.start_time.strftime(t('matches.format_time'))
              %td.text-center
                - if match.winner_id.blank?
                  = '-'
                - else
                  = [players[match.winner_id][:surname], players[match.winner_id][:name]].join(' ')
              - if current_user.present? and current_user.super_admin?
                %td.admin-list-actions
                  .admin-list-actions__link
                    = link_to edit_match_path(match), class:'btn btn-ghost btn-square' do
                      %span.material-icons.admin-actions__link__icon= 'edit'
                  .admin-list-actions__link
                    = link_to match, method: :delete, data: { confirm: t('matches.delete') }, class: 'btn btn-sstm btn-square' do
                      %span.material-icons.admin-actions__link__icon= 'delete'

    .player-list-footer
      = render 'paginator', matches: @matches, anchor: 'stats'

  -# .tab-pane.fade#data{role: 'tabpanel', 'aria-labelledby'=>'data-tab'}
  -#   %table.table.table-hover.table-borderless
  -#     %thead.table-header
  -#       %tr
  -#         %th= link_to t('matches.gamer_tag'), matches_path(search: params[:search], filter: params[:filter], 'filter-data': params['filter-data'], sort: 'gamer_tag', order: 'asc', anchor: 'data')
  -#         %th.text-center= link_to t('matches.canton'), matches_path(search: params[:search], filter: params[:filter], 'filter-data': params['filter-data'], sort: 'canton', order: 'asc', anchor: 'data')
  -#         %th.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= link_to t('matches.age'), matches_path(search: params[:search], filter: params[:filter], 'filter-data': params['filter-data'], sort: 'birth_year', order: 'asc', anchor: 'data')
  -#         %th.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= link_to t('matches.gender'), matches_path(search: params[:search], filter: params[:filter], 'filter-data': params['filter-data'], sort: 'gender', order: 'asc', anchor: 'data')
  -#         %th.text-center= link_to t('matches.comment'), matches_path(search: params[:search], filter: params[:filter], 'filter-data': params['filter-data'], sort: 'comment', order: 'desc', anchor: 'data')

  -#     %tbody.table-content.with-show
  -#       - if @matches.any?
  -#         - @matches.each_with_index do |player, i|
  -#           %tr{'data-id': player.id, 'data-component'=>'player'}
  -#             %td
  -#               - if player.main_characters.any?
  -#                 - player.main_characters[0...1].each do |char|
  -#                   - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
  -#                     = image_tag "characters/#{char}.png", height: '25px', width: '25px'
  -#               - else
  -#                 .div{style: 'display: inline;'}
  -#                   %span.material-icons{style: 'vertical-align: middle; height: 25px; width: 25px;'}= 'help'
  -#               = player.prefix.present? ? "#{player.prefix} | #{player.gamer_tag}" : player.gamer_tag
  -#             %td.text-center
  -#               - if player.canton.present?
  -#                 = image_tag "cantons/#{player.canton}.svg", height: '20px', width: '20px'
  -#                 = t("defines.cantons.#{player.canton}")
  -#             %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= player.birth_year.nil? ? '' : (Date.today.year - player.birth_year)
  -#             %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= (player.gender.nil? or player.gender.empty?) ? "" : t("defines.genders.#{player.gender}")
  -#             %td.text-center= truncate(player.comment, length: 60)

  -#             - if current_user.present? and current_user.super_admin?
  -#               %td.admin-list-actions
  -#                 .admin-list-actions__link
  -#                   = link_to edit_player_path(player), class:'btn btn-ghost btn-square' do
  -#                     %span.material-icons.admin-actions__link__icon= 'edit'

    .player-list-footer
      = render 'paginator', matches: @matches, anchor: 'data'

  - if !@matches.any?
    %p{style: 'text-align: center;'}
    = t('matches.no_matches_found')

app/views/matches/new.html.haml
.row
  .col
    %h1.page__title= t('matches.create')

.row
  .col
    = render 'form', match: @match

app/views/matches/payment.html.haml
.row
  .col
    %h1.page__title= t('players.payment')

.row
  .col
    = form_for :date, url: payment_matches_path, method: :get, role: 'form', class:'form' do |f|
      .field.form-group
        = f.label :month, t('calendar.buttonText.month')
        - select_array = t('calendar.monthNames').each_with_object({}).with_index { |(elem, hash), index| hash[elem] = index + 1 }
        = f.select :month, options_for_select(select_array, params.dig('date','month') || Time.now.month), class: 'form-control'
        = f.label :year, t('calendar.buttonText.year')
        = f.select :year, options_for_select((2021..Time.now.year), params.dig('date','year') || Time.now.year), class: 'form-control'
      .actions.form-group
        = f.submit class:'btn btn-ghost', value: t('players.amount')

-if @payment
  = render 'show_payment', month_payment: @month_payment
-else
  .row
    %p Выберете месяц